version: '3.1'
services:
  app:
    container_name: url_shortener
    build: .
    restart: always
    volumes:
      - ./server.js:/app/server.js
    ports:
      - 3000:3000
    environment:
      API_ENDPOINT: 'http://localhost:3000'
      FIREBASE_SERVICE_ACCOUNT: './serviceAccount.json'
      FIREBASE_DATABASE_URL: 'https://url-shortener-7aacf.firebaseio.com'
      API_TOKEN: 'my-token'
    command: sh -c './node_modules/.bin/pm2 start ./server.js --watch --no-daemon'
