version: '3.1'
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    entrypoint: redis-server --appendonly yes
  app:
    container_name: url_shortener
    build: .
    restart: always
    volumes:
      - ./server.js:/app/server.js
    ports:
      - 3000:3000
    environment:
      API_ENDPOINT: 'http://localhost:3000'
      # API_TOKEN: 'daniel'
    depends_on:
      - redis
    links:
      - redis
    command: sh -c './node_modules/.bin/pm2 start ./server.js --watch --no-daemon'
