version: '3.1'
services:
  app:
    container_name: url_shortener
    image: dflourusso/url-shortener
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./serviceAccount.json:/app/serviceAccount.json
    environment:
      API_ENDPOINT: 'http://your-host.com'
      FIREBASE_DATABASE_URL: 'https://url-shortener.firebaseio.com'
      API_TOKEN: 'my-token'
    command: sh -c './node_modules/.bin/pm2 start ./server.js --watch --no-daemon'
